[workspace]
authors = ["jaimemcc <j.mccutcheon@uit.no>"]
channels = ["conda-forge"]
name = "bazzino"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.13"
numpy = ">=2.4.2,<3"
pandas = ">=3.0.0,<4"
dill = ">=0.4.1,<0.5"
matplotlib = ">=3.10.8,<4"
ipykernel = ">=7.2.0,<8"
scipy = ">=1.17.0,<2"
scikit-learn = ">=1.8.0,<2"
statsmodels = ">=0.14.6,<0.15"
seaborn = ">=0.13.2,<0.14"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
tdt = ">=0.7.3, <0.8"
trompy = ">=0.16.1, <0.17"
bazzino = { path = ".", editable = true }
